import { GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut, User } from 'firebase/auth';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import StripeAccount from 'src/components/connect/stripe-account';
import ProductList from 'src/components/connect/product-list';
import { auth } from 'src/lib/firebase';
import styles from 'src/styles/Home.module.css';

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    onAuthStateChanged(auth, (firebaseUser) => {
      setUser(firebaseUser);
    });
  }, []);

  const login = () => {
    signInWithPopup(auth, new GoogleAuthProvider());
  };

  const logout = () => {
    signOut(auth);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {user ? <button onClick={logout}>ログアウト</button> : <button onClick={login}>ログイン</button>}
        {user && <p>{user.displayName}さんようこそ</p>}
        {user && <StripeAccount user={user} />}
        {user && <ProductList />}
      </main>
    </div>
  );
};

export default Home;
