import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from 'src/styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <nav className={styles.nav}>
          <Link href='/payments'>
            <a>商品の販売</a>
          </Link>
          <Link href='/billing'>
            <a>サブスクリプション</a>
          </Link>
          <Link href='/connect'>
            <a>マーケットプレイス</a>
          </Link>
        </nav>
      </main>
    </div>
  );
};

export default Home;
