import { GoogleAuthProvider, onAuthStateChanged, signInWithPopup, signOut, User } from 'firebase/auth';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import CustomerPortal from 'src/components/payments/customer-portal';
import ProductList from 'src/components/payments/product-list';
import PurchaseList from 'src/components/payments/purchase-list';
import { auth } from 'src/lib/firebase';
import styles from 'src/styles/Home.module.css';

const Home: NextPage = () => {
  const [user, setUser] = useState<User | null>(null);

  useEffect(() => {
    // ログインユーザーの監視とセット
    onAuthStateChanged(auth, (firebaseUser) => {
      setUser(firebaseUser);
    });
  }, []);

  // ログイン
  const login = () => {
    signInWithPopup(auth, new GoogleAuthProvider());
  };

  // ログアウト
  const logout = () => {
    signOut(auth);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {user ? <button onClick={logout}>ログアウト</button> : <button onClick={login}>ログイン</button>}
        {user && <p>{user.displayName}さんようこそ</p>}
        {user && <ProductList user={user}></ProductList>}
        {user && <PurchaseList user={user}></PurchaseList>}
        {user && <CustomerPortal />}
      </main>
    </div>
  );
};

export default Home;
